### PR TITLE
font-awesome-sass / Font Awesome 5 support

### PR DESCRIPTION
**Pull request by jason-hobbs**
Updated font-awesome-sass to latest which is font awesome 5.  Changed fa class to fas.

### CODE REVIEW

**Comment by flowersw** [comment]
I would love to see this pulled in, as my project uses FA5 and will need to use a different wysiwyg editor if it's not. I've not complaints about wysiwyg-rails so far other than the above.

**Comment by stefanneculai** [comment]
@jason-hobbs could you please limit your PR to the `wysiwyg-rails.gemspec` changes?

**Comment by jason-hobbs** [comment]
I reverted it back to the .gemspec only.

**Comment by chamnap** [comment]
Does this PR got released it yet? Look like it haven't.

**Pull request merged**
